### ISSUE TITLE
isFuture / isOngoing / isPast Not working after craft add postfix to fields in content table

### ISSUE THREAD

**Issue by taher-amici** [studioespresso/craft-date-range#26]
isFuture / isOngoing / isPast is not working after craft cms recent update
https://user-images.githubusercontent.com/51078042/139384619-4e9de187-5d1c-4412-96b9-4eaea14cbf63.png
give this error.

Additional info
  Craft version: 3.7.12
  PHP version: 7.4
  Database driver & version: 8.0.23
  Date range Plugin: 2.3.0

**Comment by janhenckens** [comment]
@taher-amici Could you share how you're using the field in your template? I can't seem to reproduce the issue on my end.

**Comment by taher-amici** [comment]
yeah sure I was getting error when using .isFuture() or any other filer on my craft query like this:
`craft.entries.section('events').limit(5).orderBy('eventDate asc').isFuture(fieldHandle)`

**Comment by janhenckens** [comment]
Should be fixed in today's update!

**Comment by carolineboeykens** [comment]
Is it possible that you are now using the field name instead of the field handle? It broke some things here after the update

<img width="1434" alt="Screenshot 2021-11-03 at 14 31 07" src="https://user-images.githubusercontent.com/42932673/140069659-4bf6be31-2557-4c69-9d15-4b1c6a0d452e.png">

**Comment by taher-amici** [comment]
yes I also get the error after the update still not working.
`{% set entries = craft.entries.section('events').isFuture('eventDate') %}`
https://user-images.githubusercontent.com/51078042/140071381-6f810961-4158-4fc0-8de0-0c78e126e78e.png

**Comment by janhenckens** [comment]
Whoops, my bad! My fields had the same name & handle so it didn't pop up in my testing. Just pushed a fix for this, call you install that and try? @carolineboeykens @taher-amici

**Comment by taher-amici** [comment]
Sure, Thanks for quick response mate. @janhenckens

**Comment by janhenckens** [comment]
I'm assuming this is fix now so closing the issue, let me know if it's not :)
